
# postgres:
#     image: postgres:9.6
#     # volumes:
#         # - "./data:/var/lib/postgresql/data"
#     environment:
#         - POSTGRES_USER=segment
#         - POSTGRES_DB=segment
#         - POSTGRES_PASSWORD=segment
#     ports:
#         - "5432:5432"

#  postgres_host:
#    ports:
#      - "5433:5432"
#    volumes:
#      - /mnt/sda1/var/pgdata/:/var/lib/postgresql/data

# mongodb:
#     image: mongo:latest
#     # container_name: "mongodb"
#     # environment:
#     #   - MONGO_DATA_DIR=/data
#     #   - MONGO_LOG_DIR=/dev/null
#     # volumes:
#     #   - ./data/db:/data/db
#     ports:
#         - 27017:27017
#     # command: mongod --dbpath --smallfiles --logpath=/dev/null # --quiet
#     environment:
#         - MONGODB_USER="segment" 
#         - MONGODB_PASS="segment"
#     # networks:
#     #     default:

selenium-hub:
  image: selenium/hub:3.8.1
  # image: selenium/hub
  ports:
  - 4444:4444
#   volumes:
#   - ${PROJECT_BROKER}:/opt/app
  # environment:
  # - GRID_MAX_SESSION=10
  # - GRID_BROWSER_TIMEOUT=100000
  # - GRID_TIMEOUT=90000
  # - GRID_NEW_SESSION_WAIT_TIMEOUT=20
  # expose:
  # - 4444

chrome:
  image: selenium/node-chrome:3.8.1
  # image: selenium/node-chrome
  links:
  - selenium-hub:hub
  # ports:
  # - "4000:80"
  volumes:
  # - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  - ./scrapy/data:/home/seluser/Downloads
  # - ${PROJECT_BROKER}:/opt/app
  # environment:   
  # - HUB_PORT_4444_TCP_ADDR=selenium-hub  # erro aparente
  # shm_size: 1536m
  # depends_on:
  # - selenium-hub
  # expose:
  # - 5555

scrapy_broker:
  restart: always
  build: ./broker
#   volumes:
#   - ${PROJECT_BROKER}:/opt/app
  ports:
  - "5000:5000"
  env_file:
  # - ./scrapy/.env
  - ./docker-base.env
  links:
  - selenium-hub:hub
#   environment:
#   - URL_BROKER=${URL_BROKER}
#   - HOST_BROKER=${HOST_BROKER}
#   - BROKER_CPF_CNPJ=${BROKER_CPF_CNPJ}
#   - BROKER_PASSWORD=${BROKER_PASSWORD}
#   - BROKER_DT_NASC=${BROKER_DT_NASC}
#   - BROKER_SIGNATURE=${BROKER_SIGNATURE}
#   depends_on:
  # - selenium-hub
  # - chrome
  expose:
  - 5000