  scrapy_broker:
    restart: always
    build: .
    ports:
    - "5018:5018"
    links:
    - selenium-hub:hub
    environment:
    - URL_BROKER=${URL_BROKER}
    - HOST_BROKER=${HOST_BROKER}
    - BROKER_CPF_CNPJ=${BROKER_CPF_CNPJ}
    - BROKER_PASSWORD=${BROKER_PASSWORD}
    - BROKER_DT_NASC=${BROKER_DT_NASC}
    - BROKER_SIGNATURE=${BROKER_SIGNATURE}
    expose:
    - 5018

  chrome:
    image: selenium/node-chrome:3.8.1
    links:
    - selenium-hub:hub
    expose:
    - 4000

  selenium-hub:
    image: selenium/hub:3.8.1
    ports:
    - 4444:4444
    environment:
    - GRID_MAX_SESSION=10
    - GRID_BROWSER_TIMEOUT=100000
    - GRID_TIMEOUT=90000
    - GRID_NEW_SESSION_WAIT_TIMEOUT=20
