set SECRET_KEY=asdfasdf2342asdfa

set DOCKER_HOST=tcp://0.0.0.0:2375/

set WORKER_BROKER_URL=redis://127.0.0.1:6378/0
set WORKER_BACKEND_URL=redis://127.0.0.1:6378/0

set WORKER_BROKER_URL=redis://172.31.85.181:6378/0
set WORKER_BACKEND_URL=redis://172.31.85.181:6378/0
 
set REDIS_PORT=6378
set REDIS_DB=0

set HOST_BROKER=http://127.0.0.1:4444/wd/hub

echo %NEWVAR%
setx EC2_CERT "%USERPROFILE%\aws\cert.pem"
set URL_BROKER=https://www.clear.com.br/pit/daytrade/Main
set BROKER_CPF_CNPJ=<YOUR_BROKER_CPF_CNPJ>
set BROKER_PASSWORD=<YOUR_BROKER_PASSWORD>
set BROKER_DT_NASC=<YOUR_BROKER_DT_NASC>
set BROKER_SIGNATURE=<YOUR_BROKER_SIGNATURE>

set URL_FINANCE=https://www.santander.com.br/br/pessoa-fisica/santander
set CPF_FINANCE=<YOUR_CPF_FINANCE>
set PASS_FINANCE=<YOUR_PASS_FINANCE>
set DIR_LOCAL_DRIVER=<YOUR_DIR_LOCAL_DRIVER>
set DIR_LOCAL_DATA=<YOUR_DIR_LOCAL_DATA>

set no_proxy=192.168.99.100
set PROJECT_BROKER=<YOUR_PROJECT_BROKER>